### ISSUE TITLE
Make a hasFlashPlayer.min.js.

### ISSUE THREAD

**Issue by simsicon** [sofish/hasFlashPlayer.js#1]
It would be a good practice to make hasFlashPlayer.js readable and hasFlashPlayer.min.js compressed.

**Comment by sofish** [comment]
the hasFlashPlayer.js is **_already_** compressed, and the source code is lying in the `/src` folder

![Cute-Asian-maid-wink-smile](https://f.cloud.github.com/assets/153183/113442/965e9d04-6b56-11e2-80e8-4c1ffa54b1c7.gif)

**Comment by simsicon** [comment]
:100:
